type argument =
  | No_argument
  | Integer
  | Input_file of string list
  | Output_file

type t = {
  flag : string;
  spec : Arg.spec;
  description : string;
  argument : argument;
}

let option ?(argument = No_argument) flag spec description =
  { flag; spec; description; argument }

let speclist options =
  List.map (fun option -> option.flag, option.spec, option.description) options

let shell_quote value =
  "'" ^ String.concat "'\\''" (String.split_on_char '\'' value) ^ "'"

let bash_identifier command =
  String.map (function '-' -> '_' | character -> character) command

let bash command options =
  let function_name = "_" ^ bash_identifier command in
  let flags =
    "-help --help --completion " ^
    String.concat " " (List.map (fun option -> option.flag) options)
  in
  let file_flags =
    options
    |> List.filter_map (fun option ->
           match option.argument with
           | Input_file _ | Output_file -> Some option.flag
           | No_argument | Integer -> None)
    |> String.concat "|"
  in
  let integer_flags =
    options
    |> List.filter_map (fun option ->
           match option.argument with
           | Integer -> Some option.flag
           | No_argument | Input_file _ | Output_file -> None)
    |> String.concat "|"
  in
  let argument_cases =
    (if file_flags = "" then "" else
       Printf.sprintf
         "    %s) COMPREPLY=( $(compgen -f -- \"$cur\") ); return ;;\n"
         file_flags) ^
    (if integer_flags = "" then "" else
       Printf.sprintf "    %s) return ;;\n" integer_flags) ^
    "    --completion) COMPREPLY=( $(compgen -W \"bash zsh fish\" -- \"$cur\") ); return ;;\n"
  in
  Printf.printf
    "# Generated by tools/generate_completions.sh; do not edit.\n\
     %s()\n\
     {\n\
       local cur prev\n\
       COMPREPLY=()\n\
       cur=${COMP_WORDS[COMP_CWORD]}\n\
       prev=${COMP_WORDS[COMP_CWORD-1]}\n\
       case \"$prev\" in\n\
     %s\
       esac\n\
       if [[ $cur == -* ]]; then\n\
         COMPREPLY=( $(compgen -W %s -- \"$cur\") )\n\
       fi\n\
     }\n\
     complete -F %s %s\n"
    function_name argument_cases (shell_quote flags) function_name command

let zsh_argument = function
  | No_argument -> ""
  | Integer -> ":integer:"
  | Output_file -> ":output file:_files"
  | Input_file [] -> ":file:_files"
  | Input_file _ -> ":file:_files"

let zsh_escape value =
  value
  |> String.to_seq
  |> Seq.flat_map (function
       | '\'' -> String.to_seq "'\\''"
       | '[' -> String.to_seq "\\["
       | ']' -> String.to_seq "\\]"
       | character -> Seq.return character)
  |> String.of_seq

let zsh command options =
  Printf.printf
    "#compdef %s\n# Generated by tools/generate_completions.sh; do not edit.\n\n_arguments \\\n"
    command;
  let entries =
    ("'(-help --help)'{-help,--help}'[Show command-line help]'" ::
     "'--completion[Generate a shell completion]:shell:(bash zsh fish)'" ::
     List.map (fun option ->
       Printf.sprintf "'%s[%s]%s'"
         option.flag (zsh_escape option.description) (zsh_argument option.argument)) options)
  in
  List.iteri (fun index entry ->
      Printf.printf "  %s%s\n" entry
        (if index = List.length entries - 1 then "" else " \\")) entries

let fish_escape value =
  String.concat "\\'" (String.split_on_char '\'' value)

let fish_condition = function
  | No_argument -> ""
  | Integer -> " -r"
  | Output_file | Input_file [] -> " -r -F"
  | Input_file suffixes ->
    Printf.sprintf " -r -a '(__fish_complete_suffix %s)'"
      (String.concat " " suffixes)

let fish command options =
  Printf.printf "# Generated by tools/generate_completions.sh; do not edit.\n";
  Printf.printf "complete -c %s -o help -l help -d 'Show command-line help'\n" command;
  Printf.printf "complete -c %s -l completion -r -a 'bash zsh fish' -d 'Generate a shell completion'\n" command;
  List.iter (fun option ->
      if option.flag <> "--" then begin
        let old_style_flag = String.sub option.flag 1 (String.length option.flag - 1) in
        Printf.printf "complete -c %s -o %s%s -d '%s'\n"
          command old_style_flag (fish_condition option.argument)
          (fish_escape option.description)
      end) options

let generate command options shell =
  match shell with
  | "bash" -> bash command options
  | "zsh" -> zsh command options
  | "fish" -> fish command options
  | _ ->
    Printf.eprintf "Unknown shell %S (expected bash, zsh, or fish).\n" shell;
    exit 2

let handle command options =
  if Array.length Sys.argv = 3 && Sys.argv.(1) = "--completion" then begin
    generate command options Sys.argv.(2);
    exit 0
  end
