(menhir
 (modules yaccparser)
 (flags (--unused-tokens))
  ; unused-tokens
)
(ocamllex lexer)

(rule
 (targets generated_parser.ml grammar.html)
 (deps ../expr_grammar_action.g)
 (action
  (run %{bin:alpaga} -g %{dep:../expr_grammar_action.g} -pml generated_parser.ml -html grammar.html)))

(rule
  (target config.ml)
   (deps
    ../configure
    ../opts.sh
    (env_var ECOMP_RUNTIME_DIR)
    (source_tree ../runtime))
    (action
     (chdir ..
      (bash "source ./opts.sh && exec ./configure $CONF_OPTS")
    ))
)

(rule
 (target report_assets.ml)
 (deps ecomp-report-style.css ecomp-report.js)
 (action
  (with-stdout-to %{target}
   (progn
    (echo "let css = {ecomp_css|")
    (cat ecomp-report-style.css)
    (echo "|ecomp_css}")
    (echo "let javascript = {ecomp_js|")
    (cat ecomp-report.js)
    (echo "|ecomp_js}")))))

(executables
 (names main runner report_main test_lexer)
 (public_names ecomp ecomp-run ecomp-report -)
 (package ecomp)
 (libraries
   yojson
   lwt
   websocket
   websocket-lwt-unix
   menhirLib
 )
 (flags (:standard -warn-error -A -w -27 -w -33 -w -9 -w -39))
)
