
let heapsize = ref 10240
let tokens_save : string option ref = ref None
let ast_save : string option ref = ref None
let e_save : string option ref = ref None
let e_run = ref false
let cfg_save : string option ref = ref None
let cfg_save_after_cp : string option ref = ref None
let cfg_save_after_dae : string option ref = ref None
let cfg_save_after_ne : string option ref = ref None
let cfg_run = ref false
let cfg_run_after_cp = ref false
let cfg_run_after_dae = ref false
let cfg_run_after_ne = ref false
let rtl_save : string option ref = ref None
let rtl_run = ref false
let linear_save : string option ref = ref None
let linear_save_after_dse : string option ref = ref None
let linear_run = ref false
let linear_run_after_dse = ref false
let ltl_save : string option ref = ref None
let ltl_run = ref false
let ltl_debug = ref false
let riscv_dump : string option ref = ref None
let riscv_exe_save : string option ref = ref None
let riscv_run = ref false
let params : int list ref = ref []
let input_file : string option ref = ref None
let output_json : string ref = ref "/dev/null"
let nostart = ref false
let nostats = ref false
let has_mul = ref true
let no_cfg_constprop = ref false
let no_cfg_dae = ref false
let no_cfg_ne = ref false
let no_linear_dse = ref false

let alloc_order_st = ref true
let naive_regalloc = ref true
let rig_save : string option ref = ref None
let handwritten_lexer = ref Config.lex_hand
let alpaga_parser = ref Config.alpaga_parser
let timeout = ref 3.0
let verbose = ref false
